#
# Private Git repositories
# SSH private key for the repository is provided in the 'private-repository-one' secret under the key 'sshPrivateKey'
#
---
apiVersion: v1
kind: Secret
metadata:
  name: git-repository-one
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:aws-samples/eks-gitops-crossplane-argocd.git   
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACB8+lYaAU/MQh3DdBojWVz+4XDoBqIvT3rltZfXqZWBAQAAAJj3m8/Z95vP
    2QAAAAtzc2gtZWQyNTUxOQAAACB8+lYaAU/MQh3DdBojWVz+4XDoBqIvT3rltZfXqZWBAQ
    AAAEDdDGAkKZa0PVIPiMyKa3248GMbw+WBMq+/z9lr6SM1eXz6VhoBT8xCHcN0GiNZXP7h
    cOgGoi9PeuW1l9eplYEBAAAAD3ZpamlAc2FyYXRoeS5pbwECAwQFBg==
    -----END OPENSSH PRIVATE KEY-----  
